package:
  name: perl-dbi
  version: '1.634'

source:
  fn: DBI-1.634.tar.gz
  url: https://cpan.metacpan.org/authors/id/T/TI/TIMB/DBI-1.634.tar.gz

build:
  number: 1

requirements:
  build:
    - perl-threaded
    - perl-app-cpanminus
    - perl-module-build
  run:
    - perl-threaded

about:
  home: https://metacpan.org/pod/DBI
  license: Perl
  summary: Database independent interface for Perl
