package:
  name: bio-vcf
  version: "0.9.1"
build:
  number: 2
source:
  fn: bio-vcf-5637d6d.tar.gz
  url: https://github.com/pjotrp/bioruby-vcf/archive/5637d6d.tar.gz
requirements:
  build:
    - ruby
  run:
    - ruby
test:
  commands:
    - "bio-vcf --help | grep 'Usage: bio-vcf'"
about:
  home: https://github.com/pjotrp/bioruby-vcf
  license: MIT
  summary: Smart VCF parser 
