package:
  name: perl-pod-simple
  version: "3.28"

source:
  fn: Pod-Simple-3.32.tar.gz
  url: http://search.cpan.org/CPAN/authors/id/M/MA/MARCGREEN/Pod-Simple-3.32.tar.gz
  #md5: 
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - Pod::Simple
    - Pod::Simple::BlackBox
    - Pod::Simple::Checker
    - Pod::Simple::Debug
    - Pod::Simple::DumpAsText
    - Pod::Simple::DumpAsXML
    - Pod::Simple::HTML
    - Pod::Simple::HTMLBatch
    - Pod::Simple::HTMLLegacy
    - Pod::Simple::LinkSection
    - Pod::Simple::Methody
    - Pod::Simple::Progress
    - Pod::Simple::PullParser
    - Pod::Simple::PullParserEndToken
    - Pod::Simple::PullParserStartToken
    - Pod::Simple::PullParserTextToken
    - Pod::Simple::PullParserToken
    - Pod::Simple::RTF
    - Pod::Simple::Search
    - Pod::Simple::SimpleTree
    - Pod::Simple::Text
    - Pod::Simple::TextContent
    - Pod::Simple::TiedOutFH
    - Pod::Simple::Transcode
    - Pod::Simple::TranscodeDumb
    - Pod::Simple::TranscodeSmart
    - Pod::Simple::XHTML
    - Pod::Simple::XMLOutStream

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://search.cpan.org/dist/Pod-Simple/
  license: perl_5
  summary: 'framework for parsing Pod'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
