package:
  name: perl-statistics-descriptive
  version: '3.0609'

source:
  fn: Statistics-Descriptive-3.0609.tar.gz
  url: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Statistics-Descriptive-3.0609.tar.gz

build:
  number: 0

requirements:
  build:
    - perl
    - perl-app-cpanminus
    - perl-module-build
  run:
    - perl

about:
  home: https://metacpan.org/pod/Statistics::Descriptive
  license: Perl
  summary: Module of basic descriptive statistical functions