package:
  name: pybedtools
  version: '0.7.6'

source:
  url: https://pypi.python.org/packages/source/p/pybedtools/pybedtools-0.7.6.tar.gz
  fn: pybedtools-0.7.6.tar.gz
  md5: b910c7be9bf26a1508a071e03dfbb7f7

build:
  number: 1

requirements:
  build:
    - python
    - six
    - pysam >=0.8.1
    - setuptools
    - pandas
    - cython

  run:
    - python
    - six
    - pysam >=0.8.1
    - pandas

test:
  imports:
    - pybedtools

about:
  home: https://github.com/daler/pybedtools
  license: MIT
  summary: Wraps BEDTools for use in Python and adds many additional features.
