about:
    home: 'https://ccb.jhu.edu/software/hisat2/index.shtml'
    license: GPLv3
    summary: graph-based alignment of next generation sequencing reads to a population of genomes
package:
    name: hisat2
    version: 2.0.1beta
requirements:
    build:
        - python
    run:
        - python
test:
    commands:
        - hisat2 --version

source:
  fn: hisat2-2.0.1-beta-Linux_x86_64.zip #[linux]
  url: ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/downloads/hisat2-2.0.1-beta-Linux_x86_64.zip #[linux]
  md5: f2fa54657ccc52eb3a70938197cca607 #[linux]

  fn: hisat2-2.0.1-beta-OSX_x86_64.zip #[osx]
  url: ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/downloads/hisat2-2.0.1-beta-OSX_x86_64.zip #[osx]
  md5: 24a848f93b439b4466ba0fbe51956951 #[osx]
