about:
    home: https://bitbucket.org/dan2097/opsin/
    license: Artistic License 2.0
    summary: OPSIN is a Java(1.6+) library for IUPAC name-to-structure conversion offering high recall and precision on organic chemical nomenclature.
package:
    name: opsin
    version: 1.4.0
build:
  number: 1
source:
    fn: opsin-1.4.0-jar-with-dependencies.jar
    url: https://bitbucket.org/dan2097/opsin/downloads/opsin-1.4.0-jar-with-dependencies.jar
requirements:
  build:
  run:
    - java-jdk  >=6
test:
    commands:
      - opsin --help
