package:
  name: rapmap
  version: "v0.1.0pre"
source:
  fn: v0.1.0-pre.tar.gz
  url: https://github.com/COMBINE-lab/RapMap/releases/download/v0.1.0-pre/RapMap-0.1.0-pre_CentOS5.tar.gz
  sha256: 9ec27f9c85db49fd605d80a78b084c9b5bb72d8bac408bfd90bca8137c05ca77
build:
  number: 2
about:
  home: https://github.com/COMBINE-lab/RapMap
  license: GPL
  summary: Rapid sensitive and accurate read mapping via quasi-mapping
test:
  commands:
    - rapmap --help
