package:
  name: bcbreport
  version: "0.99.21"
build:
  number: 1
source:
  git_url: https://github.com/lpantano/bcbio.coverage
  git_tag: cc9eb9c

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - bcbreport

about:
  home: https://github.com/lpantano/bcbio.coverage
  license: MIT License
  summary: Rmd templates for bcbio-nextgen analysis
