package:
  name: pybigwig
  version: '0.2.4'

source:
  #git_url: https://github.com/dpryan79/pyBigWig
  fn: pyBigWig-0.2.4.tar.gz
  sha256: e6515d3a2a127d1731fea83ebd81ba215ab9543f956ed0209e883c5d18dab73d
  url: https://pypi.python.org/packages/source/p/pyBigWig/pyBigWig-0.2.4.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - curl
  run:
    - python
    - curl
test:
  imports:
    - pyBigWig

  commands:
    - nosetests pyBigWigTest -s -v

  requires:
    - nose

about:
  home: https://github.com/dpryan79/pyBigWig
  license: MIT
  summary: A python extension written in C for quick access to bigWig files.
