package:
  name: ete2
  version: '2.2.1072'

source:
  fn: ete2-2.2.1072.tar.gz
  url: https://pypi.python.org/packages/source/e/ete2/ete2-2.2.1072.tar.gz
  md5: 2864ed149ac22afbc533199c9f8cb133

build:
  number: 2
  skip: true # [not py27]

requirements:
  build:
    - python
    - setuptools
    - pyqt
    - numpy
    - lxml
    - mysql-python

  run:
    - python
    - setuptools
    - pyqt
    - numpy
    - lxml
    - mysql-python

test:
  imports:
    - ete2

about:
  home: http://etetoolkit.org/
  license: GPLv3
  summary: Phylogenetic tree analyses and exploration
