package:
  name: perl-archive-zip
  version: '1.55'

source:
  fn: Archive-Zip-1.55.tar.gz
  url: https://cpan.metacpan.org/authors/id/P/PH/PHRED/Archive-Zip-1.55.tar.gz

build:
  number: 0

requirements:
  build:
    - perl
    - perl-app-cpanminus
    - perl-module-build
  run:
    - perl

about:
  home: https://metacpan.org/pod/Archive::Zip
  license: Perl
  summary: Provide an interface to ZIP archive files