about:
  home: http://eigen.tuxfamily.org
  license: MPL2
  summary: "Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms."
build:
  number: 1
package:
  name: eigen3
  version: '3.2'
requirements:
  build:
  - cmake ==3.2.3
source:
  fn: 3.2.6.tar.bz2
  sha256: 8a3352f9a5361fe90e451a7305fb1896fc7f771dc16cc0edd8e6b157f52c343e
  url: https://bitbucket.org/eigen/eigen/get/3.2.6.tar.bz2
test:
  commands:
    - ls -l $PREFIX/eigen3/include/ &> /dev/null
    - ls -l $PREFIX/eigen3/share/ &> /dev/null
