package:
  name: perl-archive-extract
  version: '0.76'

source:
  fn: Archive-Extract-0.76.tar.gz
  url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Archive-Extract-0.76.tar.gz

build:
  number: 1

requirements:
  build:
    - perl-threaded
    - perl-app-cpanminus
  run:
    - perl-threaded

about:
  home: https://metacpan.org/pod/Archive::Extract
  license: Perl
  summary: A generic archive extracting mechanism
