package:
  name: deeptools
  version: '2.0.1'

source:
  fn: deepTools-2.0.1.tar.gz
  url: https://pypi.python.org/packages/source/d/deepTools/deepTools-2.0.1.tar.gz
  md5: 985143b6d92ee934be93d0284a8fedfb

build:
  number: 0
  skip: True # [not py27]

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.8.0
    - scipy >=0.15.0
    - matplotlib >=1.4.0
    - pysam >=0.8.2
    - bx-python >=0.7.2
  run:
    - python
    - pybigwig >=0.2.3
    - numpy >=1.8.0
    - scipy >=0.15.0
    - matplotlib >=1.4.0
    - pysam >=0.8.2
    - bx-python >=0.7.2

test:
  imports:
    - deeptools

  commands:
    - bamCompare --version

about:
  home: https://github.com/fidelram/deepTools
  license: GPL3
  summary: A set of user-friendly tools for normalization and visualzation of deep-sequencing data
