package:
  name: perl-io-html
  version: "1.001"

source:
  fn: IO-HTML-1.001.tar.gz
  url: http://cpan.metacpan.org/authors/id/C/CJ/CJM/IO-HTML-1.001.tar.gz
  md5: 3f8958718844dc96b9f6946f21d70d22
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl
    - perl-extutils-makemaker
    - perl-carp
    - perl-scalar-list-utils
    - perl-encode
    - perl-exporter
    - perl-file-temp
    - perl-test-simple

  run:
    - perl
    - perl-encode
    - perl-exporter
    - perl-carp

test:
  # Perl 'use' tests
  imports:
    - IO::HTML

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://metacpan.org/pod/IO-HTML
  license: perl_5
  summary: 'Open an HTML file with automatic charset detection'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
