package:
  name: stringtie
  version: "1.2.0"
source:
  fn: v1.2.0.tar.gz
  url: https://github.com/gpertea/stringtie/archive/v1.2.0.tar.gz
  sha256: 0e2a9124d578a68f2444703d96bbc755037dfbc4657d4b2d0ee9724c8abc4b37
build:
  number: 1
about:
  home: http://ccb.jhu.edu/software/stringtie/
  license: Artistic License 2.0
  summary: Transcriptome assembly and quantification for RNA-seq
test:
  commands:
    - stringtie --version
