package:
  name: perl-compress-raw-zlib
  version: '2.069'

source:
  fn: Compress-Raw-Zlib-2.069.tar.gz
  url: https://cpan.metacpan.org/authors/id/P/PM/PMQS/Compress-Raw-Zlib-2.069.tar.gz

build:
  number: 0

requirements:
  build:
    - perl
    - perl-app-cpanminus
    - perl-module-build
  run:
    - perl

about:
  home: https://metacpan.org/pod/Compress::Raw::Zlib
  license: Perl
  summary: Low-Level Interface to zlib compression library