package:
  name: gemini
  version: "0.18.0"
build:
  number: 7
  skip: True # [not py27]
source:
  fn: gemini-3efc092.tar.gz
  url: https://github.com/arq5x/gemini/archive/3efc092.tar.gz
  #fn: gemini-0.18.0.tar.gz
  #url: https://pypi.python.org/packages/source/g/gemini/gemini-0.18.0.tar.gz
  md5: e0d9f68dd6ad1023e1d4e5ff667106e0

requirements:
  build:
    - python
    - setuptools
    - bcolz
    - bottle
    - bx-python
    - cyordereddict
    - cython
    - cyvcf2
    - geneimpacts
    - inheritance
    - ipyparallel
    - ipython-cluster-helper
    - jinja2
    - networkx
    - numexpr
    - numpy
    - openpyxl
    - pandas
    - pybedtools
    - pysam
    - pyyaml
    - scipy
    - unidecode
  run:
    - python
    - bcolz
    - bottle
    - bx-python
    - cyordereddict
    - cython
    - cyvcf2
    - geneimpacts
    - inheritance
    - ipyparallel
    - ipython-cluster-helper
    - jinja2
    - networkx
    - numexpr
    - numpy
    - openpyxl
    - pandas
    - pybedtools
    - pysam
    - pyyaml
    - scipy
    - unidecode
    - grabix

test:
  commands:
    - gemini -h
  imports:
    - gemini

about:
  home: https://github.com/arq5x/gemini
  license: MIT License
  summary: a lightweight db framework for disease and population genetics.
