package:
  name: burrito-fillings
  version: "0.1.1"

source:
  fn: burrito-fillings-0.1.1.tar.gz
  url: https://pypi.python.org/packages/source/b/burrito-fillings/burrito-fillings-0.1.1.tar.gz
  md5: ea65051e674aedfad8bbfdfa63f2c4d8

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - scikit-bio ==0.2.3
    - burrito ==0.9.1

  run:
    - python
    - scikit-bio ==0.2.3
    - burrito ==0.9.1

test:
  # Python imports
  imports:
    - bfillings

about:
  home: https://github.com/biocore/burrito-fillings
  license: BSD License
  summary: 'burrito-fillings: burrito application controllers for bioinformatics'

