about:
  home: https://github.com/lpantano/seqclsuter
  license: MIT
  summary: small RNA analysis from NGS data

package:
  name: seqcluster
  version: '1.1.13'

source:
  git_url: https://github.com/lpantano/seqcluster
  git_rev: 99f2fac
build:
  number: 3
  skip: True # [not py27]

requirements:
  build:
    - python
    - setuptools
    - gcc
  run:
    - python
    - pyyaml
    - pysam >=0.8.1
    - pandas
    - pybedtools
    - progressbar
    - matplotlib

test:
  commands:
    - seqcluster cluster -h
  imports:
    - seqcluster
