package:
  name: perl-vcftools-vcf
  version: '0.953'

source:
  fn: Vcf-0.953.tar.gz
  url: https://github.com/chapmanb/vcftools-cpan/archive/v0.953.tar.gz

build:
  number: 0

requirements:
  build:
    - perl
    - perl-app-cpanminus
    - perl-module-build
  run:
    - perl

test:
  imports:
    - Vcf

about:
  home: https://github.com/chapmanb/vcftools-cpan
  license: LGPLv3
  summary: cpanm ready distribution of VCFtools Perl libraries